# Generated by Django 5.0.4 on 2024-05-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfolder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='dare',
            new_name='date',
        ),
    ]
