# Generated by Django 5.0.4 on 2024-05-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolder', '0002_rename_dare_portfolio_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
