# Generated by Django 5.0.4 on 2024-05-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolder', '0005_alter_team_lavozim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='services',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='team',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
